# Generated by Django 4.0.3 on 2022-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0007_color_size_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
