# Generated by Django 4.0.3 on 2022-04-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0009_remove_orderitem_color_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bastama.size'),
        ),
    ]
