# Generated by Django 4.0.3 on 2022-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0010_remove_productattribute_size_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='size',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
