# Generated by Django 4.0.3 on 2022-05-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0014_lookbook_lookwithproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookwithproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='lookwithproduct',
            name='product_attr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bastama.productattribute'),
            preserve_default=False,
        ),
    ]
