# Generated by Django 4.0.3 on 2022-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0015_remove_lookwithproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(max_length=20)),
                ('cc_expiry', models.CharField(max_length=5)),
                ('cc_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
