# Generated by Django 4.0.3 on 2022-05-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bastama', '0016_payment_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bastama.customer'),
            preserve_default=False,
        ),
    ]
